define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Screen1 generated by Appery.io
     * @module Screen1
     */

    APP.controller('Screen1', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {

        /**
         * user controller variables
         */
        $scope.businessList = Apperyio.EntityAPI('BusinessList');

        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
            var requestData = {}; /*|button_mapping|onbeforesend|86FC17BB-7B83-A74C-258C-9CF7B5E1DBD1||8843|*/

            // read more about using rest services: https://links.appery.io/ve-snippet-rest
            Apperyio.get("Disrupt_Yelp_businesses_get")(requestData).then( /*|service_bookmark|bookmark|86FC17BB-7B83-A74C-258C-9CF7B5E1DBD1||4486|*/

            function(success) { // success callback
                (function mapping5712(success, $scope) {
                    var businessList_scope = $scope.businessList;
                    for (var i = 0, l = success.data.businesses.length; i < l; i++) {
                        _.set(businessList_scope, '[' + i + '].name', success.data.businesses[i].name);
                        _.set(businessList_scope, '[' + i + '].url', success.data.businesses[i].url);
                        _.set(businessList_scope, '[' + i + '].image', success.data.businesses[i].image_url);
                        _.set(businessList_scope, '[' + i + '].phone', success.data.businesses[i].phone);
                        _.set(businessList_scope, '[' + i + '].review', success.data.businesses[i].review_count);
                        _.set(businessList_scope, '[' + i + '].rating', success.data.businesses[i].rating);
                        _.set(businessList_scope, '[' + i + '].lat', success.data.businesses[i].coordinates.latitude);
                        _.set(businessList_scope, '[' + i + '].lng', success.data.businesses[i].coordinates.longitude);
                    }
                    $scope.businessList = businessList_scope; /*|button_mapping|onsuccess|86FC17BB-7B83-A74C-258C-9CF7B5E1DBD1||5712|*/
                })(success, $scope);

            }, function(error) { // callback to handle request error
            }, function(notify) { // notify callback, can fire few times
            });

        };

    }

});